// ═══════════════════════════════════════════════════
//  YOGA POSES DATABASE
//  Each pose has: name, Sanskrit, emoji, difficulty,
//  description, target joint angles (min/max), tips
// ═══════════════════════════════════════════════════

const POSES = [
  {
    id: 'mountain',
    name: 'Mountain Pose',
    sanskrit: 'Tadasana',
    emoji: '🧍',
    difficulty: 'beginner',
    description: 'Foundation of all standing poses. Stand tall with feet together.',
    angles: {
      leftKnee:  { min: 165, max: 185, label: 'Left Knee' },
      rightKnee: { min: 165, max: 185, label: 'Right Knee' },
      leftHip:   { min: 160, max: 185, label: 'Left Hip' },
      rightHip:  { min: 160, max: 185, label: 'Right Hip' },
      leftElbow: { min: 155, max: 185, label: 'Left Elbow' },
      rightElbow:{ min: 155, max: 185, label: 'Right Elbow' },
      leftShoulder:  { min: 0, max: 25, label: 'Left Shoulder' },
      rightShoulder: { min: 0, max: 25, label: 'Right Shoulder' },
    },
    tips: ['Stand with feet hip-width apart', 'Engage your core', 'Shoulders relaxed and down', 'Arms alongside body']
  },
  {
    id: 'warrior1',
    name: 'Warrior I',
    sanskrit: 'Virabhadrasana I',
    emoji: '🥷',
    difficulty: 'intermediate',
    description: 'Powerful standing pose building strength and stability.',
    angles: {
      leftKnee:  { min: 85, max: 100, label: 'Front Knee' },
      rightKnee: { min: 155, max: 185, label: 'Back Knee' },
      leftHip:   { min: 85, max: 110, label: 'Hip Bend' },
      rightHip:  { min: 155, max: 180, label: 'Back Hip' },
      leftElbow: { min: 155, max: 185, label: 'Left Elbow' },
      rightElbow:{ min: 155, max: 185, label: 'Right Elbow' },
      leftShoulder:  { min: 160, max: 185, label: 'Arms Raised' },
      rightShoulder: { min: 160, max: 185, label: 'Arms Raised' },
    },
    tips: ['Front knee over ankle', 'Back foot at 45°', 'Arms straight overhead', 'Square hips forward']
  },
  {
    id: 'warrior2',
    name: 'Warrior II',
    sanskrit: 'Virabhadrasana II',
    emoji: '⚔️',
    difficulty: 'intermediate',
    description: 'Standing pose with arms extended horizontally, building endurance.',
    angles: {
      leftKnee:  { min: 85, max: 100, label: 'Front Knee' },
      rightKnee: { min: 155, max: 185, label: 'Back Knee' },
      leftHip:   { min: 85, max: 110, label: 'Left Hip' },
      rightHip:  { min: 85, max: 110, label: 'Right Hip' },
      leftElbow: { min: 155, max: 185, label: 'Left Elbow' },
      rightElbow:{ min: 155, max: 185, label: 'Right Elbow' },
      leftShoulder:  { min: 80, max: 100, label: 'Left Shoulder' },
      rightShoulder: { min: 80, max: 100, label: 'Right Shoulder' },
    },
    tips: ['Arms parallel to floor', 'Gaze over front hand', 'Shoulders relaxed', 'Front knee over ankle']
  },
  {
    id: 'tree',
    name: 'Tree Pose',
    sanskrit: 'Vrksasana',
    emoji: '🌳',
    difficulty: 'beginner',
    description: 'Balancing pose on one leg that improves focus and stability.',
    angles: {
      leftKnee:  { min: 155, max: 185, label: 'Standing Leg' },
      rightKnee: { min: 50, max: 90, label: 'Bent Knee' },
      leftHip:   { min: 155, max: 185, label: 'Standing Hip' },
      rightHip:  { min: 45, max: 80, label: 'Open Hip' },
      leftElbow: { min: 155, max: 185, label: 'Left Elbow' },
      rightElbow:{ min: 155, max: 185, label: 'Right Elbow' },
      leftShoulder:  { min: 155, max: 185, label: 'Arms Up' },
      rightShoulder: { min: 155, max: 185, label: 'Arms Up' },
    },
    tips: ['Fix gaze on one point', 'Standing leg firm', 'Hips level', 'Hands in prayer or overhead']
  },
  {
    id: 'downdog',
    name: 'Downward Dog',
    sanskrit: 'Adho Mukha Svanasana',
    emoji: '🐕',
    difficulty: 'beginner',
    description: 'Inverted V-shape pose stretching entire posterior chain.',
    angles: {
      leftKnee:  { min: 155, max: 185, label: 'Left Knee' },
      rightKnee: { min: 155, max: 185, label: 'Right Knee' },
      leftHip:   { min: 55, max: 80, label: 'Hip Angle' },
      rightHip:  { min: 55, max: 80, label: 'Hip Angle' },
      leftElbow: { min: 155, max: 185, label: 'Left Arm' },
      rightElbow:{ min: 155, max: 185, label: 'Right Arm' },
      leftShoulder:  { min: 155, max: 185, label: 'Left Shoulder' },
      rightShoulder: { min: 155, max: 185, label: 'Right Shoulder' },
    },
    tips: ['Heels toward floor', 'Spine long and straight', 'Head between arms', 'Hips high toward ceiling']
  },
  {
    id: 'cobra',
    name: 'Cobra Pose',
    sanskrit: 'Bhujangasana',
    emoji: '🐍',
    difficulty: 'beginner',
    description: 'Backbend that opens the chest and strengthens the spine.',
    angles: {
      leftKnee:  { min: 155, max: 185, label: 'Left Leg' },
      rightKnee: { min: 155, max: 185, label: 'Right Leg' },
      leftHip:   { min: 155, max: 185, label: 'Hip Flat' },
      rightHip:  { min: 155, max: 185, label: 'Hip Flat' },
      leftElbow: { min: 140, max: 165, label: 'Left Elbow' },
      rightElbow:{ min: 140, max: 165, label: 'Right Elbow' },
      leftShoulder:  { min: 15, max: 50, label: 'Left Shoulder' },
      rightShoulder: { min: 15, max: 50, label: 'Right Shoulder' },
    },
    tips: ['Palms flat under shoulders', 'Elbows close to body', 'Chest lifted', 'Gaze slightly up']
  },
  {
    id: 'child',
    name: "Child's Pose",
    sanskrit: 'Balasana',
    emoji: '🙇',
    difficulty: 'beginner',
    description: 'Restorative resting pose that relaxes the back and hips.',
    angles: {
      leftKnee:  { min: 20, max: 55, label: 'Left Knee Bend' },
      rightKnee: { min: 20, max: 55, label: 'Right Knee Bend' },
      leftHip:   { min: 30, max: 70, label: 'Left Hip Fold' },
      rightHip:  { min: 30, max: 70, label: 'Right Hip Fold' },
      leftElbow: { min: 155, max: 185, label: 'Left Arm' },
      rightElbow:{ min: 155, max: 185, label: 'Right Arm' },
      leftShoulder:  { min: 155, max: 185, label: 'Arms Extended' },
      rightShoulder: { min: 155, max: 185, label: 'Arms Extended' },
    },
    tips: ['Forehead on mat', 'Arms extended forward', 'Hips toward heels', 'Breathe deeply']
  },
  {
    id: 'triangle',
    name: 'Triangle Pose',
    sanskrit: 'Trikonasana',
    emoji: '🔺',
    difficulty: 'intermediate',
    description: 'Lateral stretch that improves flexibility in hips and spine.',
    angles: {
      leftKnee:  { min: 155, max: 185, label: 'Left Knee' },
      rightKnee: { min: 155, max: 185, label: 'Right Knee' },
      leftHip:   { min: 50, max: 80, label: 'Side Bend' },
      rightHip:  { min: 80, max: 110, label: 'Hip Open' },
      leftElbow: { min: 155, max: 185, label: 'Left Arm' },
      rightElbow:{ min: 155, max: 185, label: 'Right Arm' },
      leftShoulder:  { min: 80, max: 110, label: 'Arms Open' },
      rightShoulder: { min: 80, max: 110, label: 'Arms Open' },
    },
    tips: ['Both legs straight', 'Arms in a line', 'Rotate torso open', 'Gaze up at top hand']
  },
  {
    id: 'plank',
    name: 'Plank Pose',
    sanskrit: 'Phalakasana',
    emoji: '🏋️',
    difficulty: 'beginner',
    description: 'Core strengthening pose that builds total body stability.',
    angles: {
      leftKnee:  { min: 155, max: 185, label: 'Left Leg' },
      rightKnee: { min: 155, max: 185, label: 'Right Leg' },
      leftHip:   { min: 155, max: 185, label: 'Hip Straight' },
      rightHip:  { min: 155, max: 185, label: 'Hip Straight' },
      leftElbow: { min: 155, max: 185, label: 'Left Arm' },
      rightElbow:{ min: 155, max: 185, label: 'Right Arm' },
      leftShoulder:  { min: 85, max: 100, label: 'Left Shoulder' },
      rightShoulder: { min: 85, max: 100, label: 'Right Shoulder' },
    },
    tips: ['Body in straight line', 'Core engaged', 'Wrists under shoulders', 'Don\'t let hips sag']
  },
  {
    id: 'seated_forward',
    name: 'Seated Forward Bend',
    sanskrit: 'Paschimottanasana',
    emoji: '🤸',
    difficulty: 'beginner',
    description: 'Intense stretch for the entire posterior body.',
    angles: {
      leftKnee:  { min: 155, max: 185, label: 'Left Knee' },
      rightKnee: { min: 155, max: 185, label: 'Right Knee' },
      leftHip:   { min: 55, max: 85, label: 'Hip Fold' },
      rightHip:  { min: 55, max: 85, label: 'Hip Fold' },
      leftElbow: { min: 135, max: 175, label: 'Left Elbow' },
      rightElbow:{ min: 135, max: 175, label: 'Right Elbow' },
      leftShoulder:  { min: 155, max: 185, label: 'Left Shoulder' },
      rightShoulder: { min: 155, max: 185, label: 'Right Shoulder' },
    },
    tips: ['Hinge from hips, not waist', 'Keep spine long', 'Reach for feet or shins', 'Don\'t round the back excessively']
  },
  {
    id: 'bridge',
    name: 'Bridge Pose',
    sanskrit: 'Setu Bandha Sarvangasana',
    emoji: '🌉',
    difficulty: 'beginner',
    description: 'Backbend that opens the chest and strengthens glutes.',
    angles: {
      leftKnee:  { min: 80, max: 100, label: 'Left Knee' },
      rightKnee: { min: 80, max: 100, label: 'Right Knee' },
      leftHip:   { min: 130, max: 165, label: 'Left Hip Lift' },
      rightHip:  { min: 130, max: 165, label: 'Right Hip Lift' },
      leftElbow: { min: 155, max: 185, label: 'Left Arm' },
      rightElbow:{ min: 155, max: 185, label: 'Right Arm' },
      leftShoulder:  { min: 10, max: 40, label: 'Shoulder Press' },
      rightShoulder: { min: 10, max: 40, label: 'Shoulder Press' },
    },
    tips: ['Feet flat on mat', 'Knees hip-width apart', 'Drive hips up', 'Chin away from chest']
  },
  {
    id: 'pigeon',
    name: 'Pigeon Pose',
    sanskrit: 'Kapotasana',
    emoji: '🕊️',
    difficulty: 'advanced',
    description: 'Deep hip opener that releases tension in glutes and hip flexors.',
    angles: {
      leftKnee:  { min: 50, max: 80, label: 'Front Knee' },
      rightKnee: { min: 155, max: 185, label: 'Back Leg' },
      leftHip:   { min: 50, max: 80, label: 'Front Hip' },
      rightHip:  { min: 155, max: 185, label: 'Back Hip' },
      leftElbow: { min: 135, max: 175, label: 'Left Arm' },
      rightElbow:{ min: 135, max: 175, label: 'Right Arm' },
      leftShoulder:  { min: 155, max: 185, label: 'Left Shoulder' },
      rightShoulder: { min: 155, max: 185, label: 'Right Shoulder' },
    },
    tips: ['Front shin parallel to mat', 'Square your hips', 'Fold forward slowly', 'Breathe into the hips']
  },
  {
    id: 'chair',
    name: 'Chair Pose',
    sanskrit: 'Utkatasana',
    emoji: '🪑',
    difficulty: 'intermediate',
    description: 'Squat-like pose building thigh and core strength.',
    angles: {
      leftKnee:  { min: 90, max: 120, label: 'Left Knee' },
      rightKnee: { min: 90, max: 120, label: 'Right Knee' },
      leftHip:   { min: 90, max: 120, label: 'Left Hip' },
      rightHip:  { min: 90, max: 120, label: 'Right Hip' },
      leftElbow: { min: 155, max: 185, label: 'Left Arm' },
      rightElbow:{ min: 155, max: 185, label: 'Right Arm' },
      leftShoulder:  { min: 155, max: 185, label: 'Arms Raised' },
      rightShoulder: { min: 155, max: 185, label: 'Arms Raised' },
    },
    tips: ['Knees behind toes', 'Arms overhead', 'Weight in heels', 'Engage your core']
  },
  {
    id: 'eagle',
    name: 'Eagle Pose',
    sanskrit: 'Garudasana',
    emoji: '🦅',
    difficulty: 'advanced',
    description: 'Complex balance pose improving concentration and coordination.',
    angles: {
      leftKnee:  { min: 120, max: 150, label: 'Standing Knee' },
      rightKnee: { min: 80, max: 110, label: 'Wrapped Knee' },
      leftHip:   { min: 120, max: 155, label: 'Hip Bend' },
      rightHip:  { min: 80, max: 110, label: 'Wrapped Hip' },
      leftElbow: { min: 85, max: 105, label: 'Wrapped Elbow' },
      rightElbow:{ min: 85, max: 105, label: 'Wrapped Elbow' },
      leftShoulder:  { min: 80, max: 105, label: 'Shoulder Wrap' },
      rightShoulder: { min: 80, max: 105, label: 'Shoulder Wrap' },
    },
    tips: ['Focus on a still point', 'Cross arms at elbow', 'Sink into the stance', 'Squeeze thighs together']
  },
  {
    id: 'lotus',
    name: 'Lotus Pose',
    sanskrit: 'Padmasana',
    emoji: '🪷',
    difficulty: 'advanced',
    description: 'Classic meditation pose requiring hip flexibility.',
    angles: {
      leftKnee:  { min: 40, max: 70, label: 'Left Knee' },
      rightKnee: { min: 40, max: 70, label: 'Right Knee' },
      leftHip:   { min: 75, max: 105, label: 'Left Hip' },
      rightHip:  { min: 75, max: 105, label: 'Right Hip' },
      leftElbow: { min: 130, max: 170, label: 'Left Arm' },
      rightElbow:{ min: 130, max: 170, label: 'Right Arm' },
      leftShoulder:  { min: 10, max: 40, label: 'Left Shoulder' },
      rightShoulder: { min: 10, max: 40, label: 'Right Shoulder' },
    },
    tips: ['Sit on a cushion if needed', 'Spine upright', 'Hands on knees', 'Breathe slowly and deeply']
  }
];

// MoveNet keypoint indices
const KP = {
  nose: 0, leftEye: 1, rightEye: 2, leftEar: 3, rightEar: 4,
  leftShoulder: 5, rightShoulder: 6,
  leftElbow: 7, rightElbow: 8,
  leftWrist: 9, rightWrist: 10,
  leftHip: 11, rightHip: 12,
  leftKnee: 13, rightKnee: 14,
  leftAnkle: 15, rightAnkle: 16
};
